services:
  backend:
    build:
      context: ./bookbee-backend
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - postgres

  postgres:
    image: postgres:17.2
    container_name: postgres_container
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./development_bookbee_dataset.sql:/docker-entrypoint-initdb.d/dataset.sql
  
  frontend:
    build:
        context: ./bookbee-frontend
        dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "80:3000"
    depends_on:
      - backend
